services:
  backend-beta:
    image: ghcr.io/almostprohibited/backend:beta
    restart: unless-stopped
    environment:
      API_PORT: 4002
    ports:
      - 27017:27017
      - 4002:4002
    network_mode: bridge
